Repository autoatml/autoplex, pull requests merged in 2024-11, with the labels that each got.

#212 Add workflow to autoupdate devcontainer.json version tags on new release
  .github/workflows/update_devcontainer.yml
Labels: enhancement, dependencies

#217 Revise lammps compilation
  Dockerfile
  tests/test_data/.pytest-split-durations
Labels: dependencies

#221 raise pr via update_devcontainer.yml
  .github/workflows/update_devcontainer.yml
Labels: bug, dependencies

#224 move to src layout
  pyproject.toml
  src/autoplex/__init__.py
  src/autoplex/auto/__init__.py
  src/autoplex/auto/phonons/__init__.py
  src/autoplex/auto/phonons/flows.py
  src/autoplex/auto/phonons/jobs.py
  src/autoplex/auto/rss/__init__.py
  src/autoplex/auto/rss/flows.py
  src/autoplex/auto/rss/jobs.py
  src/autoplex/auto/rss/rss_default_configuration.yaml
  src/autoplex/benchmark/__init__.py
  src/autoplex/benchmark/phonons/__init__.py
  src/autoplex/benchmark/phonons/flows.py
  src/autoplex/benchmark/phonons/jobs.py
  src/autoplex/benchmark/phonons/utils.py
  src/autoplex/benchmark/rss/__init__.py
  src/autoplex/data/__init__.py
  src/autoplex/data/common/__init__.py
  src/autoplex/data/common/flows.py
  src/autoplex/data/common/jobs.py
  src/autoplex/data/common/utils.py
  src/autoplex/data/phonons/__init__.py
  src/autoplex/data/phonons/flows.py
  src/autoplex/data/phonons/jobs.py
  src/autoplex/data/phonons/utils.py
  src/autoplex/data/rss/__init__.py
  src/autoplex/data/rss/flows.py
  src/autoplex/data/rss/jobs.py
  src/autoplex/data/rss/utils.py
  src/autoplex/fitting/__init__.py
  src/autoplex/fitting/common/__init__.py
  src/autoplex/fitting/common/flows.py
  src/autoplex/fitting/common/jobs.py
  src/autoplex/fitting/common/mlip-phonon-defaults.json
  src/autoplex/fitting/common/mlip-rss-defaults.json
  src/autoplex/fitting/common/regularization.py
  src/autoplex/fitting/common/utils.py
  src/autoplex/fitting/phonons/__init__.py
  src/autoplex/fitting/phonons/flows.py
  src/autoplex/fitting/phonons/jobs.py
  src/autoplex/fitting/rss/README.md
  src/autoplex/fitting/rss/__init__.py
  src/autoplex/fitting/rss/flows.py
  src/autoplex/fitting/rss/jobs.py
  tests/test_data/.pytest-split-durations
Labels: enhancement

#235 Update devcontainer.json version tag
  .devcontainer/devcontainer.json
Labels: dependencies

#238 Misc CI workflow improvements
  .github/workflows/docker-publish.yml
  .github/workflows/python-package.yml
  .github/workflows/update_devcontainer.yml
  README.md
  codecov.yml
  docs/dev/dev_install.md
  tests/test_data/.pytest-split-durations
Labels: enhancement, dependencies

#258 Make sure that supercell_matrices of single-atom-displaced and rattled supercells are the same per default
  src/autoplex/auto/phonons/flows.py
  src/autoplex/auto/phonons/jobs.py
  src/autoplex/data/phonons/flows.py
  src/autoplex/data/phonons/jobs.py
  src/autoplex/fitting/common/mlip-phonon-defaults.json
  tests/auto/test_auto_flows.py
  tests/auto/test_auto_jobs.py
  tests/fitting/test_fitting_utils.py
Labels: enhancement

#277 Pin lammps ci and in Docs
  .github/workflows/python-package.yml
  Dockerfile
  README.md
  docs/user/setup.md
Labels: dependencies
