Repository autoatml/autoplex, pull requests merged in 2025-02, with the labels that each got.

#339 Update test durations file
  tests/test_data/.pytest-split-durations
Labels: automated-pr

#340 Update changelog with latest release notes
  CHANGELOG.md
Labels: automated-pr

#341 Update devcontainer.json version tag
  .devcontainer/devcontainer.json
Labels: automated-pr

#288 Enable NEP interface
  .devcontainer/devcontainer.json
  Dockerfile
  README.md
  docs/user/installation/installation.md
  pyproject.toml
  src/autoplex/auto/phonons/jobs.py
  src/autoplex/auto/rss/jobs.py
  src/autoplex/data/common/jobs.py
  src/autoplex/data/common/utils.py
  src/autoplex/data/phonons/flows.py
  src/autoplex/data/rss/jobs.py
  src/autoplex/data/rss/utils.py
  src/autoplex/fitting/common/flows.py
  src/autoplex/fitting/common/jobs.py
  src/autoplex/fitting/common/utils.py
  tests/auto/phonons/test_flows.py
  tests/conftest.py
  tests/fitting/common/test_flows.py
  tests/fitting/common/test_jobs.py
  tests/fitting/common/test_utils.py
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/inputs/nep.in
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/inputs/test.xyz
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/inputs/train.xyz
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/energy_test.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/energy_train.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/force_test.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/force_train.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/loss.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/nep.restart
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/nep.txt
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/stress_test.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/stress_train.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/virial_test.out
  tests/test_data/fitting/NEP/LiCl_complete_dft_vs_ml_benchmark_workflow/outputs/virial_train.out
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/inputs/nep.in
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/inputs/test.xyz
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/inputs/train.xyz
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/energy_test.out
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/force_test.out
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/loss.out
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/nep.restart
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/nep.txt
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/stress_test.out
  tests/test_data/fitting/NEP/LiCl_mlipfitmaker/outputs/virial_test.out
Labels: documentation, enhancement, dependencies

#342 Update test durations file
  tests/test_data/.pytest-split-durations
Labels: automated-pr

#347 Update test durations file
  tests/test_data/.pytest-split-durations
Labels: automated-pr

#349 Include executable tutorials in documentation website
  .github/workflows/docs.yml
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  docs/user/tutorials.md
  pyproject.toml
  tutorials/index.md
  tutorials/mock_vasp.py
  tutorials/tutorial_phonon.ipynb
  tutorials/tutorial_rss.ipynb
Labels: documentation
