Repository autoatml/autoplex, pull requests merged in 2025-04, with the labels that each got.

#364 Update test durations file
  tests/test_data/.pytest-split-durations
Labels: automated-pr

#367 update dependencies
  .github/workflows/python-package.yml
  pyproject.toml
Labels: dependencies, housekeeping

#368 Update changelog with latest release notes
  CHANGELOG.md
Labels: automated-pr

#372 Update devcontainer.json version tag
  .devcontainer/devcontainer.json
Labels: automated-pr

#374 Upgrade pypi release action
  .github/workflows/python-publish.yml
Labels: housekeeping
